apiVersion: advanced.mdaops.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: advanced/v1alpha1/cluster
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    clusterType: REPLICASET
    projectId: PROJECT ID
    replicationSpecs:
    - regionConfigs:
      - analyticsSpecs:
        - instanceSize: M10
          nodeCount: 1
        electableSpecs:
        - instanceSize: M10
          nodeCount: 3
        priority: 7
        providerName: AWS
        regionName: US_EAST_1
