apiVersion: global.mongoatlas.io/v1alpha1
kind: ClusterConfig
metadata:
  annotations:
    meta.upbound.io/example-id: global/v1alpha1/clusterconfig
  labels:
    testing.upbound.io/example-name: config
  name: config
spec:
  forProvider:
    clusterName: NAME OF CLUSTER
    customZoneMappings:
    - location: CA
      zone: Zone 1
    managedNamespaces:
    - collection: publishers
      customShardKey: city
      db: mydata
      isCustomShardKeyHashed: false
      isShardKeyUnique: false
    projectId: ${mongodbatlas_advanced_cluster.test.project_id}

---

apiVersion: advancedcluster.mongoatlas.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: global/v1alpha1/clusterconfig
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    backupEnabled: true
    clusterType: GEOSHARDED
    name: <CLUSTER-NAME>
    projectSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    replicationSpecs:
    - regionConfigs:
      - electableSpecs:
        - instanceSize: M30
          nodeCount: 3
        priority: 7
        providerName: AWS
        regionName: EU_CENTRAL_1
      zoneName: Zone 1
    - regionConfigs:
      - electableSpecs:
        - instanceSize: M30
          nodeCount: 3
        priority: 7
        providerName: AWS
        regionName: US_EAST_2
      zoneName: Zone 2
