// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type EndpointServerlessInitParameters struct {

	// Human-readable label that identifies the serverless instance.
	InstanceName *string `json:"instanceName,omitempty" tf:"instance_name,omitempty"`

	// Unique 24-digit hexadecimal string that identifies the project.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Cloud provider name; AWS is currently supported
	ProviderName *string `json:"providerName,omitempty" tf:"provider_name,omitempty"`
}

type EndpointServerlessObservation struct {

	// Unique 24-hexadecimal digit string that identifies the private endpoint.
	EndpointID *string `json:"endpointId,omitempty" tf:"endpoint_id,omitempty"`

	// Unique string that identifies the PrivateLink endpoint service.
	EndpointServiceName *string `json:"endpointServiceName,omitempty" tf:"endpoint_service_name,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Human-readable label that identifies the serverless instance.
	InstanceName *string `json:"instanceName,omitempty" tf:"instance_name,omitempty"`

	// Root-relative path that identifies the Azure Private Link Service that MongoDB Cloud manages.
	PrivateLinkServiceResourceID *string `json:"privateLinkServiceResourceId,omitempty" tf:"private_link_service_resource_id,omitempty"`

	// Unique 24-digit hexadecimal string that identifies the project.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Cloud provider name; AWS is currently supported
	ProviderName *string `json:"providerName,omitempty" tf:"provider_name,omitempty"`

	// Human-readable label that indicates the current operating status of the private endpoint. Values include: RESERVATION_REQUESTED, RESERVED, INITIATING, AVAILABLE, FAILED, DELETING.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type EndpointServerlessParameters struct {

	// Human-readable label that identifies the serverless instance.
	// +kubebuilder:validation:Optional
	InstanceName *string `json:"instanceName,omitempty" tf:"instance_name,omitempty"`

	// Unique 24-digit hexadecimal string that identifies the project.
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Cloud provider name; AWS is currently supported
	// +kubebuilder:validation:Optional
	ProviderName *string `json:"providerName,omitempty" tf:"provider_name,omitempty"`
}

// EndpointServerlessSpec defines the desired state of EndpointServerless
type EndpointServerlessSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     EndpointServerlessParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider EndpointServerlessInitParameters `json:"initProvider,omitempty"`
}

// EndpointServerlessStatus defines the observed state of EndpointServerless.
type EndpointServerlessStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        EndpointServerlessObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// EndpointServerless is the Schema for the EndpointServerlesss API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,atlas-mongodb}
type EndpointServerless struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.instanceName) || (has(self.initProvider) && has(self.initProvider.instanceName))",message="spec.forProvider.instanceName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.providerName) || (has(self.initProvider) && has(self.initProvider.providerName))",message="spec.forProvider.providerName is a required parameter"
	Spec   EndpointServerlessSpec   `json:"spec"`
	Status EndpointServerlessStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// EndpointServerlessList contains a list of EndpointServerlesss
type EndpointServerlessList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []EndpointServerless `json:"items"`
}

// Repository type metadata.
var (
	EndpointServerless_Kind             = "EndpointServerless"
	EndpointServerless_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: EndpointServerless_Kind}.String()
	EndpointServerless_KindAPIVersion   = EndpointServerless_Kind + "." + CRDGroupVersion.String()
	EndpointServerless_GroupVersionKind = CRDGroupVersion.WithKind(EndpointServerless_Kind)
)

func init() {
	SchemeBuilder.Register(&EndpointServerless{}, &EndpointServerlessList{})
}
