apiVersion: cloud.mongoatlas.io/v1alpha1
kind: BackupSnapshotExportBucket
metadata:
  annotations:
    meta.upbound.io/example-id: cloud/v1alpha1/backupsnapshotexportbucket
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    bucketName: example-bucket
    cloudProvider: AWS
    iamRoleId: '{IAM_ROLE_ID}'
    projectId: '{PROJECT_ID}'
