apiVersion: cloud.mongoatlas.io/v1alpha1
kind: BackupSchedule
metadata:
  annotations:
    meta.upbound.io/example-id: cloud/v1alpha1/backupschedule
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    clusterName: NAME OF CLUSTER
    policyItemDaily:
    - frequencyInterval: 1
      retentionUnit: days
      retentionValue: 2
    policyItemHourly:
    - frequencyInterval: 1
      retentionUnit: days
      retentionValue: 1
    projectId: ${mongodbatlas_advanced_cluster.my_cluster.project_id}
    referenceHourOfDay: 3
    referenceMinuteOfHour: 45
    restoreWindowDays: 4

---

apiVersion: advancedcluster.mongoatlas.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: cloud/v1alpha1/backupschedule
  labels:
    testing.upbound.io/example-name: my_cluster
  name: my-cluster
spec:
  forProvider:
    backupEnabled: true
    clusterType: REPLICASET
    name: clusterTest
    projectSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    replicationSpecs:
    - regionConfigs:
      - electableSpecs:
        - instanceSize: M10
          nodeCount: 3
        priority: 7
        providerName: AWS
        regionName: EU_CENTRAL_1
