apiVersion: custom.mongoatlas.io/v1alpha1
kind: DBRole
metadata:
  annotations:
    meta.upbound.io/example-id: custom/v1alpha1/dbrole
  labels:
    testing.upbound.io/example-name: test_role
  name: test-role
spec:
  forProvider:
    actions:
    - action: UPDATE
      resources:
      - collectionName: ""
        databaseName: anyDatabase
    - action: INSERT
      resources:
      - collectionName: ""
        databaseName: anyDatabase
    - action: REMOVE
      resources:
      - collectionName: ""
        databaseName: anyDatabase
    projectId: <PROJECT-ID>
    roleName: myCustomRole
