add_frontmatter() {
    local file="$1"
    local name=$(basename "$file" .md)
    echo '---
# generated by https://github.com/hashicorp/terraform-plugin-docs
page_title: "mongodbatlas_'"$name"' Resource - terraform-provider-mongodbatlas"
subcategory: ""
description: |-

---' | cat - "$file" > temp && mv temp "$file"
}

ls

for file in .work/mongodb/mongodbatlas/docs/resources/*.md; do
    add_frontmatter "$file"
done
