apiVersion: mongodbatlas.mongoatlas.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: mongodbatlas/v1alpha1/cluster
  labels:
    testing.upbound.io/example-name: cluster-test
  name: cluster-test
spec:
  forProvider:
    autoScalingDiskGbEnabled: true
    cloudBackup: true
    clusterType: REPLICASET
    mongoDbMajorVersion: "7.0"
    projectId: <YOUR-PROJECT-ID>
    providerInstanceSizeName: M40
    providerName: AWS
    replicationSpecs:
    - numShards: 1
      regionsConfig:
      - electableNodes: 3
        priority: 7
        readOnlyNodes: 0
        regionName: US_EAST_1
