apiVersion: event.mongoatlas.io/v1alpha1
kind: Trigger
metadata:
  annotations:
    meta.upbound.io/example-id: event/v1alpha1/trigger
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    appId: APPLICATION ID
    configCollection: COLLECTION NAME
    configDatabase: DATABASE NAME
    configFullDocument: false
    configFullDocumentBefore: false
    configMatch: |
      {
        "updateDescription.updatedFields": {
          "status": "blocked"
        }
      }
    configOperationTypes:
    - INSERT
    - UPDATE
    configProject: '{"updateDescription.updatedFields":{"status":"blocked"}}'
    configServiceId: SERVICE ID
    disabled: false
    eventProcessors:
    - awsEventbridge:
      - configAccountId: AWS ACCOUNT ID
        configRegion: AWS REGIOn
    functionId: FUNCTION ID
    projectId: PROJECT ID
    type: DATABASE
