apiVersion: encryption.mongoatlas.io/v1alpha1
kind: AtRest
metadata:
  annotations:
    meta.upbound.io/example-id: encryption/v1alpha1/atrest
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    awsKmsConfig:
    - customerMasterKeyIdSecretRef:
        key: attribute.id
        name: example-kms-key
        namespace: upbound-system
      enabled: true
      region: ${var.atlas_region}
      roleId: ${mongodbatlas_cloud_provider_access_authorization.auth_role.role_id}
    projectId: ${var.atlas_project_id}

---

apiVersion: advancedcluster.mongoatlas.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: encryption/v1alpha1/atrest
  labels:
    testing.upbound.io/example-name: cluster
  name: cluster
spec:
  forProvider:
    backupEnabled: true
    clusterType: REPLICASET
    encryptionAtRestProvider: AWS
    name: MyCluster
    projectSelector:
      matchLabels:
        testing.upbound.io/example-name: test
    replicationSpecs:
    - regionConfigs:
      - electableSpecs:
        - instanceSize: M10
          nodeCount: 3
        priority: 7
        providerName: AWS
        regionName: US_EAST_1
