apiVersion: network.mongoatlas.io/v1alpha1
kind: Container
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/container
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    atlasCidrBlock: 10.8.0.0/21
    projectId: <YOUR-PROJECT-ID>
    providerName: AWS
    regionName: US_EAST_1
