apiVersion: network.mongoatlas.io/v1alpha1
kind: Peering
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/peering
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    accepterRegionName: us-east-1
    awsAccountId: abc123abc123
    containerId: 507f1f77bcf86cd799439011
    projectId: ${local.project_id}
    providerName: AWS
    routeTableCidrBlock: 192.168.0.0/24
    vpcId: vpc-abc123abc123

---

apiVersion: network.mongoatlas.io/v1alpha1
kind: Container
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/peering
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    atlasCidrBlock: 10.8.0.0/21
    projectId: ${local.project_id}
    providerName: AWS
    regionName: US_EAST_1
