// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AtRestInitParameters struct {

	// (Block List) Amazon Web Services (AWS) KMS configuration details and encryption at rest configuration set for the specified project. (see below for nested schema)
	// Amazon Web Services (AWS) KMS configuration details and encryption at rest configuration set for the specified project.
	AwsKMSConfig []AwsKMSConfigInitParameters `json:"awsKmsConfig,omitempty" tf:"aws_kms_config,omitempty"`

	// (Block List) Details that define the configuration of Encryption at Rest using Azure Key Vault (AKV). (see below for nested schema)
	// Details that define the configuration of Encryption at Rest using Azure Key Vault (AKV).
	AzureKeyVaultConfig []AzureKeyVaultConfigInitParameters `json:"azureKeyVaultConfig,omitempty" tf:"azure_key_vault_config,omitempty"`

	// (Block List) Details that define the configuration of Encryption at Rest using Google Cloud Key Management Service (KMS). (see below for nested schema)
	// Details that define the configuration of Encryption at Rest using Google Cloud Key Management Service (KMS).
	GoogleCloudKMSConfig []GoogleCloudKMSConfigInitParameters `json:"googleCloudKmsConfig,omitempty" tf:"google_cloud_kms_config,omitempty"`

	// hexadecimal digit string that identifies your project.
	// Unique 24-hexadecimal digit string that identifies your project.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`
}

type AtRestObservation struct {

	// (Block List) Amazon Web Services (AWS) KMS configuration details and encryption at rest configuration set for the specified project. (see below for nested schema)
	// Amazon Web Services (AWS) KMS configuration details and encryption at rest configuration set for the specified project.
	AwsKMSConfig []AwsKMSConfigObservation `json:"awsKmsConfig,omitempty" tf:"aws_kms_config,omitempty"`

	// (Block List) Details that define the configuration of Encryption at Rest using Azure Key Vault (AKV). (see below for nested schema)
	// Details that define the configuration of Encryption at Rest using Azure Key Vault (AKV).
	AzureKeyVaultConfig []AzureKeyVaultConfigObservation `json:"azureKeyVaultConfig,omitempty" tf:"azure_key_vault_config,omitempty"`

	// (Block List) Details that define the configuration of Encryption at Rest using Google Cloud Key Management Service (KMS). (see below for nested schema)
	// Details that define the configuration of Encryption at Rest using Google Cloud Key Management Service (KMS).
	GoogleCloudKMSConfig []GoogleCloudKMSConfigObservation `json:"googleCloudKmsConfig,omitempty" tf:"google_cloud_kms_config,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// hexadecimal digit string that identifies your project.
	// Unique 24-hexadecimal digit string that identifies your project.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`
}

type AtRestParameters struct {

	// (Block List) Amazon Web Services (AWS) KMS configuration details and encryption at rest configuration set for the specified project. (see below for nested schema)
	// Amazon Web Services (AWS) KMS configuration details and encryption at rest configuration set for the specified project.
	// +kubebuilder:validation:Optional
	AwsKMSConfig []AwsKMSConfigParameters `json:"awsKmsConfig,omitempty" tf:"aws_kms_config,omitempty"`

	// (Block List) Details that define the configuration of Encryption at Rest using Azure Key Vault (AKV). (see below for nested schema)
	// Details that define the configuration of Encryption at Rest using Azure Key Vault (AKV).
	// +kubebuilder:validation:Optional
	AzureKeyVaultConfig []AzureKeyVaultConfigParameters `json:"azureKeyVaultConfig,omitempty" tf:"azure_key_vault_config,omitempty"`

	// (Block List) Details that define the configuration of Encryption at Rest using Google Cloud Key Management Service (KMS). (see below for nested schema)
	// Details that define the configuration of Encryption at Rest using Google Cloud Key Management Service (KMS).
	// +kubebuilder:validation:Optional
	GoogleCloudKMSConfig []GoogleCloudKMSConfigParameters `json:"googleCloudKmsConfig,omitempty" tf:"google_cloud_kms_config,omitempty"`

	// hexadecimal digit string that identifies your project.
	// Unique 24-hexadecimal digit string that identifies your project.
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`
}

type AwsKMSConfigInitParameters struct {

	// (String, Sensitive) Unique alphanumeric string that identifies an Identity and Access Management (IAM) access key with permissions required to access your Amazon Web Services (AWS) Customer Master Key (CMK).
	// Unique alphanumeric string that identifies an Identity and Access Management (IAM) access key with permissions required to access your Amazon Web Services (AWS) Customer Master Key (CMK).
	AccessKeyIDSecretRef *v1.SecretKeySelector `json:"accessKeyIdSecretRef,omitempty" tf:"-"`

	// (String, Sensitive) Unique alphanumeric string that identifies the Amazon Web Services (AWS) Customer Master Key (CMK) you used to encrypt and decrypt the MongoDB master keys.
	// Unique alphanumeric string that identifies the Amazon Web Services (AWS) Customer Master Key (CMK) you used to encrypt and decrypt the MongoDB master keys.
	CustomerMasterKeyIDSecretRef *v1.SecretKeySelector `json:"customerMasterKeyIdSecretRef,omitempty" tf:"-"`

	// (Boolean) Flag that indicates whether someone enabled encryption at rest for the specified project through Amazon Web Services (AWS) Key Management Service (KMS). To disable encryption at rest using customer key management and remove the configuration details, pass only this parameter with a value of false.
	// Flag that indicates whether someone enabled encryption at rest for the specified project through Amazon Web Services (AWS) Key Management Service (KMS). To disable encryption at rest using customer key management and remove the configuration details, pass only this parameter with a value of `false`.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// hosted MongoDB cluster nodes. The region you choose can affect network latency for clients accessing your databases. When MongoDB Cloud deploys a dedicated cluster, it checks if a VPC or VPC connection exists for that provider and region. If not, MongoDB Atlas creates them as part of the deployment. MongoDB Atlas assigns the VPC a CIDR block. To limit a new VPC peering connection to one CIDR block and region, create the connection first. Deploy the cluster after the connection starts.
	// Physical location where MongoDB Atlas deploys your AWS-hosted MongoDB cluster nodes. The region you choose can affect network latency for clients accessing your databases. When MongoDB Cloud deploys a dedicated cluster, it checks if a VPC or VPC connection exists for that provider and region. If not, MongoDB Atlas creates them as part of the deployment. MongoDB Atlas assigns the VPC a CIDR block. To limit a new VPC peering connection to one CIDR block and region, create the connection first. Deploy the cluster after the connection starts.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// hexadecimal digit string that identifies an Amazon Web Services (AWS) Identity and Access Management (IAM) role. This IAM role has the permissions required to manage your AWS customer master key.
	// Unique 24-hexadecimal digit string that identifies an Amazon Web Services (AWS) Identity and Access Management (IAM) role. This IAM role has the permissions required to manage your AWS customer master key.
	RoleID *string `json:"roleId,omitempty" tf:"role_id,omitempty"`

	// readable label of the Identity and Access Management (IAM) secret access key with permissions required to access your Amazon Web Services (AWS) customer master key.
	// Human-readable label of the Identity and Access Management (IAM) secret access key with permissions required to access your Amazon Web Services (AWS) customer master key.
	SecretAccessKeySecretRef *v1.SecretKeySelector `json:"secretAccessKeySecretRef,omitempty" tf:"-"`
}

type AwsKMSConfigObservation struct {

	// (Boolean) Flag that indicates whether someone enabled encryption at rest for the specified project through Amazon Web Services (AWS) Key Management Service (KMS). To disable encryption at rest using customer key management and remove the configuration details, pass only this parameter with a value of false.
	// Flag that indicates whether someone enabled encryption at rest for the specified project through Amazon Web Services (AWS) Key Management Service (KMS). To disable encryption at rest using customer key management and remove the configuration details, pass only this parameter with a value of `false`.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// hosted MongoDB cluster nodes. The region you choose can affect network latency for clients accessing your databases. When MongoDB Cloud deploys a dedicated cluster, it checks if a VPC or VPC connection exists for that provider and region. If not, MongoDB Atlas creates them as part of the deployment. MongoDB Atlas assigns the VPC a CIDR block. To limit a new VPC peering connection to one CIDR block and region, create the connection first. Deploy the cluster after the connection starts.
	// Physical location where MongoDB Atlas deploys your AWS-hosted MongoDB cluster nodes. The region you choose can affect network latency for clients accessing your databases. When MongoDB Cloud deploys a dedicated cluster, it checks if a VPC or VPC connection exists for that provider and region. If not, MongoDB Atlas creates them as part of the deployment. MongoDB Atlas assigns the VPC a CIDR block. To limit a new VPC peering connection to one CIDR block and region, create the connection first. Deploy the cluster after the connection starts.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// hexadecimal digit string that identifies an Amazon Web Services (AWS) Identity and Access Management (IAM) role. This IAM role has the permissions required to manage your AWS customer master key.
	// Unique 24-hexadecimal digit string that identifies an Amazon Web Services (AWS) Identity and Access Management (IAM) role. This IAM role has the permissions required to manage your AWS customer master key.
	RoleID *string `json:"roleId,omitempty" tf:"role_id,omitempty"`

	// (Boolean) Flag that indicates whether the Amazon Web Services (AWS) Key Management Service (KMS) encryption key can encrypt and decrypt data.
	// Flag that indicates whether the Amazon Web Services (AWS) Key Management Service (KMS) encryption key can encrypt and decrypt data.
	Valid *bool `json:"valid,omitempty" tf:"valid,omitempty"`
}

type AwsKMSConfigParameters struct {

	// (String, Sensitive) Unique alphanumeric string that identifies an Identity and Access Management (IAM) access key with permissions required to access your Amazon Web Services (AWS) Customer Master Key (CMK).
	// Unique alphanumeric string that identifies an Identity and Access Management (IAM) access key with permissions required to access your Amazon Web Services (AWS) Customer Master Key (CMK).
	// +kubebuilder:validation:Optional
	AccessKeyIDSecretRef *v1.SecretKeySelector `json:"accessKeyIdSecretRef,omitempty" tf:"-"`

	// (String, Sensitive) Unique alphanumeric string that identifies the Amazon Web Services (AWS) Customer Master Key (CMK) you used to encrypt and decrypt the MongoDB master keys.
	// Unique alphanumeric string that identifies the Amazon Web Services (AWS) Customer Master Key (CMK) you used to encrypt and decrypt the MongoDB master keys.
	// +kubebuilder:validation:Optional
	CustomerMasterKeyIDSecretRef *v1.SecretKeySelector `json:"customerMasterKeyIdSecretRef,omitempty" tf:"-"`

	// (Boolean) Flag that indicates whether someone enabled encryption at rest for the specified project through Amazon Web Services (AWS) Key Management Service (KMS). To disable encryption at rest using customer key management and remove the configuration details, pass only this parameter with a value of false.
	// Flag that indicates whether someone enabled encryption at rest for the specified project through Amazon Web Services (AWS) Key Management Service (KMS). To disable encryption at rest using customer key management and remove the configuration details, pass only this parameter with a value of `false`.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// hosted MongoDB cluster nodes. The region you choose can affect network latency for clients accessing your databases. When MongoDB Cloud deploys a dedicated cluster, it checks if a VPC or VPC connection exists for that provider and region. If not, MongoDB Atlas creates them as part of the deployment. MongoDB Atlas assigns the VPC a CIDR block. To limit a new VPC peering connection to one CIDR block and region, create the connection first. Deploy the cluster after the connection starts.
	// Physical location where MongoDB Atlas deploys your AWS-hosted MongoDB cluster nodes. The region you choose can affect network latency for clients accessing your databases. When MongoDB Cloud deploys a dedicated cluster, it checks if a VPC or VPC connection exists for that provider and region. If not, MongoDB Atlas creates them as part of the deployment. MongoDB Atlas assigns the VPC a CIDR block. To limit a new VPC peering connection to one CIDR block and region, create the connection first. Deploy the cluster after the connection starts.
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// hexadecimal digit string that identifies an Amazon Web Services (AWS) Identity and Access Management (IAM) role. This IAM role has the permissions required to manage your AWS customer master key.
	// Unique 24-hexadecimal digit string that identifies an Amazon Web Services (AWS) Identity and Access Management (IAM) role. This IAM role has the permissions required to manage your AWS customer master key.
	// +kubebuilder:validation:Optional
	RoleID *string `json:"roleId,omitempty" tf:"role_id,omitempty"`

	// readable label of the Identity and Access Management (IAM) secret access key with permissions required to access your Amazon Web Services (AWS) customer master key.
	// Human-readable label of the Identity and Access Management (IAM) secret access key with permissions required to access your Amazon Web Services (AWS) customer master key.
	// +kubebuilder:validation:Optional
	SecretAccessKeySecretRef *v1.SecretKeySelector `json:"secretAccessKeySecretRef,omitempty" tf:"-"`
}

type AzureKeyVaultConfigInitParameters struct {

	// (String) Azure environment in which your account credentials reside.
	// Azure environment in which your account credentials reside.
	AzureEnvironment *string `json:"azureEnvironment,omitempty" tf:"azure_environment,omitempty"`

	// hexadecimal character string that identifies an Azure application associated with your Azure Active Directory tenant.
	// Unique 36-hexadecimal character string that identifies an Azure application associated with your Azure Active Directory tenant.
	ClientIDSecretRef *v1.SecretKeySelector `json:"clientIdSecretRef,omitempty" tf:"-"`

	// (Boolean) Flag that indicates whether someone enabled encryption at rest for the specified project through Amazon Web Services (AWS) Key Management Service (KMS). To disable encryption at rest using customer key management and remove the configuration details, pass only this parameter with a value of false.
	// Flag that indicates whether someone enabled encryption at rest for the specified  project. To disable encryption at rest using customer key management and remove the configuration details, pass only this parameter with a value of `false`.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String, Sensitive) Web address with a unique key that identifies for your Azure Key Vault.
	// Web address with a unique key that identifies for your Azure Key Vault.
	KeyIdentifierSecretRef *v1.SecretKeySelector `json:"keyIdentifierSecretRef,omitempty" tf:"-"`

	// (String) Unique string that identifies the Azure Key Vault that contains your key.
	// Unique string that identifies the Azure Key Vault that contains your key.
	KeyVaultName *string `json:"keyVaultName,omitempty" tf:"key_vault_name,omitempty"`

	// (Boolean) Enable connection to your Azure Key Vault over private networking.
	// Enable connection to your Azure Key Vault over private networking.
	RequirePrivateNetworking *bool `json:"requirePrivateNetworking,omitempty" tf:"require_private_networking,omitempty"`

	// (String) Name of the Azure resource group that contains your Azure Key Vault.
	// Name of the Azure resource group that contains your Azure Key Vault.
	ResourceGroupName *string `json:"resourceGroupName,omitempty" tf:"resource_group_name,omitempty"`

	// (String, Sensitive) Private data that you need secured and that belongs to the specified Azure Key Vault (AKV) tenant (azureKeyVault.tenantID). This data can include any type of sensitive data such as passwords, database connection strings, API keys, and the like. AKV stores this information as encrypted binary data.
	// Private data that you need secured and that belongs to the specified Azure Key Vault (AKV) tenant (**azureKeyVault.tenantID**). This data can include any type of sensitive data such as passwords, database connection strings, API keys, and the like. AKV stores this information as encrypted binary data.
	SecretSecretRef *v1.SecretKeySelector `json:"secretSecretRef,omitempty" tf:"-"`

	// hexadecimal character string that identifies your Azure subscription.
	// Unique 36-hexadecimal character string that identifies your Azure subscription.
	SubscriptionIDSecretRef *v1.SecretKeySelector `json:"subscriptionIdSecretRef,omitempty" tf:"-"`

	// hexadecimal character string that identifies the Azure Active Directory tenant within your Azure subscription.
	// Unique 36-hexadecimal character string that identifies the Azure Active Directory tenant within your Azure subscription.
	TenantIDSecretRef *v1.SecretKeySelector `json:"tenantIdSecretRef,omitempty" tf:"-"`
}

type AzureKeyVaultConfigObservation struct {

	// (String) Azure environment in which your account credentials reside.
	// Azure environment in which your account credentials reside.
	AzureEnvironment *string `json:"azureEnvironment,omitempty" tf:"azure_environment,omitempty"`

	// (Boolean) Flag that indicates whether someone enabled encryption at rest for the specified project through Amazon Web Services (AWS) Key Management Service (KMS). To disable encryption at rest using customer key management and remove the configuration details, pass only this parameter with a value of false.
	// Flag that indicates whether someone enabled encryption at rest for the specified  project. To disable encryption at rest using customer key management and remove the configuration details, pass only this parameter with a value of `false`.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Unique string that identifies the Azure Key Vault that contains your key.
	// Unique string that identifies the Azure Key Vault that contains your key.
	KeyVaultName *string `json:"keyVaultName,omitempty" tf:"key_vault_name,omitempty"`

	// (Boolean) Enable connection to your Azure Key Vault over private networking.
	// Enable connection to your Azure Key Vault over private networking.
	RequirePrivateNetworking *bool `json:"requirePrivateNetworking,omitempty" tf:"require_private_networking,omitempty"`

	// (String) Name of the Azure resource group that contains your Azure Key Vault.
	// Name of the Azure resource group that contains your Azure Key Vault.
	ResourceGroupName *string `json:"resourceGroupName,omitempty" tf:"resource_group_name,omitempty"`

	// (Boolean) Flag that indicates whether the Amazon Web Services (AWS) Key Management Service (KMS) encryption key can encrypt and decrypt data.
	// Flag that indicates whether the Azure encryption key can encrypt and decrypt data.
	Valid *bool `json:"valid,omitempty" tf:"valid,omitempty"`
}

type AzureKeyVaultConfigParameters struct {

	// (String) Azure environment in which your account credentials reside.
	// Azure environment in which your account credentials reside.
	// +kubebuilder:validation:Optional
	AzureEnvironment *string `json:"azureEnvironment,omitempty" tf:"azure_environment,omitempty"`

	// hexadecimal character string that identifies an Azure application associated with your Azure Active Directory tenant.
	// Unique 36-hexadecimal character string that identifies an Azure application associated with your Azure Active Directory tenant.
	// +kubebuilder:validation:Optional
	ClientIDSecretRef *v1.SecretKeySelector `json:"clientIdSecretRef,omitempty" tf:"-"`

	// (Boolean) Flag that indicates whether someone enabled encryption at rest for the specified project through Amazon Web Services (AWS) Key Management Service (KMS). To disable encryption at rest using customer key management and remove the configuration details, pass only this parameter with a value of false.
	// Flag that indicates whether someone enabled encryption at rest for the specified  project. To disable encryption at rest using customer key management and remove the configuration details, pass only this parameter with a value of `false`.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String, Sensitive) Web address with a unique key that identifies for your Azure Key Vault.
	// Web address with a unique key that identifies for your Azure Key Vault.
	// +kubebuilder:validation:Optional
	KeyIdentifierSecretRef *v1.SecretKeySelector `json:"keyIdentifierSecretRef,omitempty" tf:"-"`

	// (String) Unique string that identifies the Azure Key Vault that contains your key.
	// Unique string that identifies the Azure Key Vault that contains your key.
	// +kubebuilder:validation:Optional
	KeyVaultName *string `json:"keyVaultName,omitempty" tf:"key_vault_name,omitempty"`

	// (Boolean) Enable connection to your Azure Key Vault over private networking.
	// Enable connection to your Azure Key Vault over private networking.
	// +kubebuilder:validation:Optional
	RequirePrivateNetworking *bool `json:"requirePrivateNetworking,omitempty" tf:"require_private_networking,omitempty"`

	// (String) Name of the Azure resource group that contains your Azure Key Vault.
	// Name of the Azure resource group that contains your Azure Key Vault.
	// +kubebuilder:validation:Optional
	ResourceGroupName *string `json:"resourceGroupName,omitempty" tf:"resource_group_name,omitempty"`

	// (String, Sensitive) Private data that you need secured and that belongs to the specified Azure Key Vault (AKV) tenant (azureKeyVault.tenantID). This data can include any type of sensitive data such as passwords, database connection strings, API keys, and the like. AKV stores this information as encrypted binary data.
	// Private data that you need secured and that belongs to the specified Azure Key Vault (AKV) tenant (**azureKeyVault.tenantID**). This data can include any type of sensitive data such as passwords, database connection strings, API keys, and the like. AKV stores this information as encrypted binary data.
	// +kubebuilder:validation:Optional
	SecretSecretRef *v1.SecretKeySelector `json:"secretSecretRef,omitempty" tf:"-"`

	// hexadecimal character string that identifies your Azure subscription.
	// Unique 36-hexadecimal character string that identifies your Azure subscription.
	// +kubebuilder:validation:Optional
	SubscriptionIDSecretRef *v1.SecretKeySelector `json:"subscriptionIdSecretRef,omitempty" tf:"-"`

	// hexadecimal character string that identifies the Azure Active Directory tenant within your Azure subscription.
	// Unique 36-hexadecimal character string that identifies the Azure Active Directory tenant within your Azure subscription.
	// +kubebuilder:validation:Optional
	TenantIDSecretRef *v1.SecretKeySelector `json:"tenantIdSecretRef,omitempty" tf:"-"`
}

type GoogleCloudKMSConfigInitParameters struct {

	// (Boolean) Flag that indicates whether someone enabled encryption at rest for the specified project through Amazon Web Services (AWS) Key Management Service (KMS). To disable encryption at rest using customer key management and remove the configuration details, pass only this parameter with a value of false.
	// Flag that indicates whether someone enabled encryption at rest for the specified  project. To disable encryption at rest using customer key management and remove the configuration details, pass only this parameter with a value of `false`.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String, Sensitive) Resource path that displays the key version resource ID for your Google Cloud KMS.
	// Resource path that displays the key version resource ID for your Google Cloud KMS.
	KeyVersionResourceIDSecretRef *v1.SecretKeySelector `json:"keyVersionResourceIdSecretRef,omitempty" tf:"-"`

	// (String, Sensitive) JavaScript Object Notation (JSON) object that contains the Google Cloud Key Management Service (KMS). Format the JSON as a string and not as an object.
	// JavaScript Object Notation (JSON) object that contains the Google Cloud Key Management Service (KMS). Format the JSON as a string and not as an object.
	ServiceAccountKeySecretRef *v1.SecretKeySelector `json:"serviceAccountKeySecretRef,omitempty" tf:"-"`
}

type GoogleCloudKMSConfigObservation struct {

	// (Boolean) Flag that indicates whether someone enabled encryption at rest for the specified project through Amazon Web Services (AWS) Key Management Service (KMS). To disable encryption at rest using customer key management and remove the configuration details, pass only this parameter with a value of false.
	// Flag that indicates whether someone enabled encryption at rest for the specified  project. To disable encryption at rest using customer key management and remove the configuration details, pass only this parameter with a value of `false`.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Boolean) Flag that indicates whether the Amazon Web Services (AWS) Key Management Service (KMS) encryption key can encrypt and decrypt data.
	// Flag that indicates whether the Google Cloud Key Management Service (KMS) encryption key can encrypt and decrypt data.
	Valid *bool `json:"valid,omitempty" tf:"valid,omitempty"`
}

type GoogleCloudKMSConfigParameters struct {

	// (Boolean) Flag that indicates whether someone enabled encryption at rest for the specified project through Amazon Web Services (AWS) Key Management Service (KMS). To disable encryption at rest using customer key management and remove the configuration details, pass only this parameter with a value of false.
	// Flag that indicates whether someone enabled encryption at rest for the specified  project. To disable encryption at rest using customer key management and remove the configuration details, pass only this parameter with a value of `false`.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String, Sensitive) Resource path that displays the key version resource ID for your Google Cloud KMS.
	// Resource path that displays the key version resource ID for your Google Cloud KMS.
	// +kubebuilder:validation:Optional
	KeyVersionResourceIDSecretRef *v1.SecretKeySelector `json:"keyVersionResourceIdSecretRef,omitempty" tf:"-"`

	// (String, Sensitive) JavaScript Object Notation (JSON) object that contains the Google Cloud Key Management Service (KMS). Format the JSON as a string and not as an object.
	// JavaScript Object Notation (JSON) object that contains the Google Cloud Key Management Service (KMS). Format the JSON as a string and not as an object.
	// +kubebuilder:validation:Optional
	ServiceAccountKeySecretRef *v1.SecretKeySelector `json:"serviceAccountKeySecretRef,omitempty" tf:"-"`
}

// AtRestSpec defines the desired state of AtRest
type AtRestSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AtRestParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AtRestInitParameters `json:"initProvider,omitempty"`
}

// AtRestStatus defines the observed state of AtRest.
type AtRestStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AtRestObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AtRest is the Schema for the AtRests API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,atlas-mongodb}
type AtRest struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	Spec   AtRestSpec   `json:"spec"`
	Status AtRestStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AtRestList contains a list of AtRests
type AtRestList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AtRest `json:"items"`
}

// Repository type metadata.
var (
	AtRest_Kind             = "AtRest"
	AtRest_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AtRest_Kind}.String()
	AtRest_KindAPIVersion   = AtRest_Kind + "." + CRDGroupVersion.String()
	AtRest_GroupVersionKind = CRDGroupVersion.WithKind(AtRest_Kind)
)

func init() {
	SchemeBuilder.Register(&AtRest{}, &AtRestList{})
}
