apiVersion: privatelink.mongoatlas.io/v1alpha1
kind: EndpointServerless
metadata:
  annotations:
    meta.upbound.io/example-id: privatelink/v1alpha1/endpointserverless
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    instanceName: ${mongodbatlas_serverless_instance.test.name}
    projectId: <PROJECT_ID>
    providerName: AWS

---

apiVersion: serverless.mongoatlas.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: privatelink/v1alpha1/endpointserverless
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    continuousBackupEnabled: true
    projectId: <PROJECT_ID>
    providerSettingsBackingProviderName: AWS
    providerSettingsProviderName: SERVERLESS
    providerSettingsRegionName: US_EAST_1
