// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type TeamsInitParameters struct {
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// +listType=set
	Usernames []*string `json:"usernames,omitempty" tf:"usernames,omitempty"`
}

type TeamsObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	TeamID *string `json:"teamId,omitempty" tf:"team_id,omitempty"`

	// +listType=set
	Usernames []*string `json:"usernames,omitempty" tf:"usernames,omitempty"`
}

type TeamsParameters struct {

	// +kubebuilder:validation:Optional
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// +kubebuilder:validation:Optional
	// +listType=set
	Usernames []*string `json:"usernames,omitempty" tf:"usernames,omitempty"`
}

// TeamsSpec defines the desired state of Teams
type TeamsSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     TeamsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TeamsInitParameters `json:"initProvider,omitempty"`
}

// TeamsStatus defines the observed state of Teams.
type TeamsStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TeamsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Teams is the Schema for the Teamss API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,atlas-mongodb}
type Teams struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.orgId) || (has(self.initProvider) && has(self.initProvider.orgId))",message="spec.forProvider.orgId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.usernames) || (has(self.initProvider) && has(self.initProvider.usernames))",message="spec.forProvider.usernames is a required parameter"
	Spec   TeamsSpec   `json:"spec"`
	Status TeamsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TeamsList contains a list of Teamss
type TeamsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Teams `json:"items"`
}

// Repository type metadata.
var (
	Teams_Kind             = "Teams"
	Teams_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Teams_Kind}.String()
	Teams_KindAPIVersion   = Teams_Kind + "." + CRDGroupVersion.String()
	Teams_GroupVersionKind = CRDGroupVersion.WithKind(Teams_Kind)
)

func init() {
	SchemeBuilder.Register(&Teams{}, &TeamsList{})
}
