name: CI

on:
  push:
    branches:
      - main
      - release-*
  pull_request: {}
  workflow_dispatch: {}

env:
  # Common versions
  GO_VERSION: '1.21'
  GOLANGCI_VERSION: 'v1.54.0'
  DOCKER_BUILDX_VERSION: 'v0.8.2'

  # Changed from UPBOUND to GHCR
  GHCR_USERNAME: ${{ github.actor }}
  GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  # ... [previous jobs remain the same until publish-artifacts] ...

  publish-artifacts:
    runs-on: ubuntu-24.04
    needs:
      - detect-noop
      - report-breaking-changes
      - lint
      - check-diff
      - unit-tests
      - local-deploy
    if: needs.detect-noop.outputs.noop != 'true'

    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3
        with:
          platforms: all

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: ${{ env.DOCKER_BUILDX_VERSION }}
          install: true

      # Changed from Upbound login to GHCR login
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          submodules: true

      # ... [cache and build steps remain the same] ...

      - name: Build Artifacts
        run: make -j2 build.all
        env:
          BUILD_ARGS: "--load"
          # Add XPKG registry override for GHCR
          XPKG_REG_ORGS: "ghcr.io/mdaops"

      - name: Upload Artifacts to GitHub
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4
        with:
          name: output
          path: _output/**

      # Modified publish step
      - name: Publish Artifacts
        run: |
          make publish BRANCH_NAME=${GITHUB_REF##*/} \
            XPKG_REG_ORGS=ghcr.io/mdaops \
            XPKG_REG_ORGS_NO_PROMOTE=ghcr.io/mdaops

